In [ ]:
import numpy as np

In [14]:
m1 = np.array([
        [2, 0, 0],
        [0, 2, 0],
        [0, 0, 1]
    ])

m2 = np.array([
        [1, 0, -1],
        [0, 1, 1],
        [0, 0, 1]
    ])


In [15]:
print(m1 @ m2)
print(m2 @ m1)
print(m2 @ m1 == m1 @ m2)

[[ 2  0 -2]
 [ 0  2  2]
 [ 0  0  1]]
[[ 2  0 -1]
 [ 0  2  1]
 [ 0  0  1]]
[[ True  True False]
 [ True  True False]
 [ True  True  True]]


In [1]:
import numpy as np

s = 0.091
c = 0.4541
x = -6.302
y = 2.4676

# Criar a matriz de rotação em coordenadas homogêneas
R = np.array([
    [c, -s, 0],
    [s,  c, 0],
    [0,                0,                1]
])

T = np.array([
    [1, 0, x],
    [0, 1, y],
    [0, 0, 1]
])

p = np.array([
    [8],
    [6],
    [1]               
])

In [3]:
res = R @ T @ p

In [5]:
res

array([[5.10200000e-04],
       [3.99965516e+00],
       [1.00000000e+00]])

In [8]:
print(round(res[0][0], 0), round(res[1][0], 0))

0.0 4.0


In [5]:
import numpy as np

T = np.array([
    [1, 0,  0],
    [0, 1, -8],
    [0, 0, 1]
])

p = np.array([
    [27],
    [4],
    [1]               
])

In [6]:
T @ p

array([[27],
       [-4],
       [ 1]])