# Aula08.Ex03 - A matriz View - Passo a passo

### Primeiro, vamos importar as bibliotecas necessárias.
Verifique no código anterior um script para instalar as dependências necessárias (OpenGL e GLFW) antes de prosseguir.

In [1]:
import numpy as np
import glm # !pip install pyglm
import math

## Calculando Matriz View

In [2]:
cameraPos = np.array([1, 0.0, 2.0]) #posicao da camera
pontoFocal = np.array([0.0, 0.0, 0.0]) #para onde ela está olhando (origem do espaço mundo)
cameraUp = np.array([0.0, 1.0, 0.0]) #vetor que aponta para cima da câmera (y = 1)

Zc = cameraPos-pontoFocal
Zc = Zc / np.linalg.norm(Zc) #normaliza, i.e., obtem vetor unitário (módulo = 1)
Zc #vetor unitário que representa o eixo Z da camera

array([0.4472136 , 0.        , 0.89442719])

In [3]:
Xc = np.cross(cameraUp, Zc)
Xc = Xc / np.linalg.norm(Xc)
Xc

array([ 0.89442719,  0.        , -0.4472136 ])

In [4]:
Yc = np.cross(Zc, Xc)
Yc

array([-0.,  1.,  0.])

In [5]:
R = [
        [Xc[0], Xc[1], Xc[2], 0.0],
        [Yc[0], Yc[1], Yc[2], 0.0],
        [Zc[0], Zc[1], Zc[2], 0.0],
        [ 0.0,  0.0,  0.0, 1.0]
    ]

T = [
        [1.0, 0.0, 0.0, -cameraPos[0]],
        [0.0, 1.0, 0.0, -cameraPos[1]],
        [0.0, 0.0, 1.0, -cameraPos[2]],
        [0.0, 0.0, 0.0, 1.0          ],        
    ]

view = np.matmul(R,T)
view

array([[ 0.89442719,  0.        , -0.4472136 ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.4472136 ,  0.        ,  0.89442719, -2.23606798],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

## Calculando Matriz View com GLM

In [6]:
cameraPos = glm.vec3(1, 0.0, 2.0)
pontoFocal = glm.vec3(0.0, 0.0, 0.0)
cameraUp = glm.vec3(0.0, 1.0, 0.0)

view = glm.lookAt(cameraPos, pontoFocal, cameraUp)
np.array(view)

array([[ 0.8944273 ,  0.        , -0.44721365, -0.        ],
       [ 0.        ,  1.0000001 ,  0.        , -0.        ],
       [ 0.4472136 , -0.        ,  0.8944272 , -2.236068  ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]],
      dtype=float32)